### ISSUE TITLE
Lacks functionality - abandoned ?

### ISSUE THREAD

**Issue by Shailevy** [courtf/Android-Reflection-Services#1]
Hi,

Whats the status of this project ? I don't see any location functions in the implementation

**Comment by courtf** [comment]
Hey, sorry for the many month absence :).  You can indeed consider this abandoned.  For what it's worth, this approach does work.  I've left the company where I implemented a partial reflection of Google Play Services, but so long as developers that wanted to use the SDK being built include Google Play Services as a dependency of their project, you can pull out all the functionality your SDK might need via reflection.

What would really be nice would be automating the generation of that code, because when I did it by hand in a rush, it was very tedious.
